# Generated by Django 3.1.3 on 2020-11-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20201031_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
